<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktif',
    'Are you sure you want to delete this user?' => 'Yakin menghapus user ini?',
    'Banned' => 'Banned',
    'Bind to IP' => 'Bind to IP',
    'Browser' => '',
    'Change own password' => 'Ganti Password anda',
    'Change password' => 'Ganti Password',
    'Changing password' => 'Ganti Password',
    'Changing password for user: ' => 'Ganti Password User: ',
    'Child permissions' => '',
    'Child roles' => '',
    'Code' => '',
    'Confirmation Token' => '',
    'Create' => 'Buat',
    'Created' => '',
    'Creating permission group' => '',
    'Current password' => 'Password saat ini',
    'Data' => '',
    'Delete' => 'Hapus',
    'Description' => 'Deskripsi',
    'E-mail' => '',
    'E-mail confirmed' => 'Email konfirmasi',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'Email aktifasi sudah dikirim, silakan cek email',
    'Edit' => '',
    'Editing' => '',
    'Editing permission group' => '',
    'Editing permission: ' => '',
    'Editing role: ' => '',
    'Editing user: ' => '',
    'For example: 123.34.56.78, 168.111.192.12' => 'contoh: 123.34.56.78, 168.111.192.12',
    'Group' => '',
    'ID' => '',
    'Inactive' => 'Tidak aktif',
    'IP' => '',
    'Language' => 'Bahasa',
    'Login' => '',
    'Name' => '',
    'OS' => '',
    'Password' => '',
    'Password has been changed' => 'Password sudah diganti',
    'Permission creation' => '',
    'Permission groups' => '',
    'Permissions' => 'Permisi',
    'Permissions for role:' => 'Permisi untuk Role',
    'Refresh routes' => '',
    'Refresh routes (and delete unused)' => '',
    'Registration IP' => 'Registrasi IP',
    'Repeat password' => 'Ulangi Password',
    'Reset' => '',
    'Role creation' => '',
    'Roles' => '',
    'Roles and permissions' => '',
    'Roles and permissions for user:' => '',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => '',
    'Save' => 'Simpan',
    'Saved' => 'Simpan',
    'Search' => 'Cari',
    'Search route' => '',
    'Settings for permission' => '',
    'Show all' => '',
    'Show only selected' => '',
    'Status' => '',
    'Superadmin' => 'Super-Admin',
    'Token' => '',
    'Too many attempts' => 'Gagal berulang kali',
    'Type' => 'Tipe',
    'Updated' => '',
    'User' => '',
    'User agent' => 'User Agent',
    'User creation' => '',
    'Users' => '',
    'Visit Time' => '',
    'Visit log' => '',
    'Wrong format. Enter valid IPs separated by comma' => 'Format salah, masukkan IP dan dipisahkan dengan koma',
    'Wrong password' => 'Password Salah',
    'You can not change own permissions' => 'Anda tidak dapat mengganti password anda',
];
