<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Captcha' => '',
    'E-mail' => '',
    'Login' => '',
    'Username' => '',
    'Authorization' => 'Otorisasi',
    'Check your E-mail for further instructions' => 'Silakan cek email untuk petunjuk lebih lanjut',
    'Check your e-mail {email} for instructions to activate account' => 'Cek email {email} untuk petunjuk aktivasi',
    'Confirm' => 'Konfirmasi',
    'Confirm E-mail' => 'E-Mail konfirmasi',
    'Continue' => 'Lanjut',
    'Could not send confirmation email' => 'Tidak dapat mengirim email konfirmasi',
    'E-mail confirmation for' => 'E-Mail konfirmasi untuk',
    'E-mail confirmed' => 'E-Mail terkonfirmasi',
    'E-mail is invalid' => 'E-Mail invalid',
    'Forgot password ?' => 'Lupa Password?',
    'Incorrect username or password.' => 'Username atau Password salah',
    'Login has been taken' => 'Login sudah terpakai',
    'Password' => '',
    'Password recovery' => 'Reset Password',
    'Password reset for' => 'Reset Password untuk',
    'Recover' => '',
    'Register' => 'Daftar',
    'Registration' => 'Pendaftaran',
    'Registration - confirm your e-mail' => 'Pendaftaran - konfirmasi email',
    'Remember me' => 'ingat saya',
    'Repeat password' => 'Ulangi Password',
    'This E-mail already exists' => 'Email ini sudah dipakai',
    'Token not found. It may be expired' => 'Token tidak ditemukan/ tidak valid',
    'Token not found. It may be expired. Try reset password once more' => 'Token tidak ditemukan/ tidak valid, silakan reset password lagi',
    'Too many attempts' => 'Gagal berulang kali',
    'Unable to send message for email provided' => 'Gagal mengirim password ke email tujuan',
    'You could not login from this IP' => 'Apakah anda tidak login dari IP ini',
];
